# Generated by Django 4.2 on 2023-04-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='logo',
            field=models.ImageField(upload_to='logos'),
        ),
    ]
